name: flushell
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  #########################
  #########################
  dio: ^5.4.3+1 # 网络请求
#  get: ^4.6.6 # 状态管理
  getwidget: ^4.0.0 # UI控件
  shared_preferences: ^2.2.3 # 配置文件
  package_info_plus: ^5.0.1 # 应用信息
  cached_network_image: ^3.3.1 # 网络图片
  connectivity_plus: ^6.0.2 # 网络状态
  device_info_plus: ^9.1.2 # 设备信息
  flutter_screenutil: ^5.9.0 # 屏幕适配
  url_launcher: ^6.2.5 # 打开浏览器
  logger: ^2.2.0 # 日志
  cool_alert: ^2.0.1 # 弹窗
  webview_flutter: ^2.0.13 # webview
  toastification: ^1.2.1
  umeng_common_sdk: ^1.2.7
#  styled_widget: ^0.4.1 # 自定义组件
#  permission_handler: ^11.3.1
#  flutter_ume: ^1.1.2

  #########################

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
#  flutter_ume: ^1.1.1+1
#  feedback: ^2.5.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - images/
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
